import { lazy, Suspense, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FiArrowDownRight, FiArrowUpRight, FiDownload, FiGithub, FiLinkedin, FiMail, FiMapPin, FiPhone, FiStar } from 'react-icons/fi';
import profile from './data/profile.json'; import navigation from './data/navigation.json'; import skills from './data/skills.json'; import experience from './data/experience.json'; import certifications from './data/certifications.json'; import agents from './data/agents.json'; import socials from './data/socials.json'; import resume from './data/resume.json';
import { Navigation } from './components/Navigation'; import { Section } from './components/Section'; import { useTheme } from './hooks/useTheme'; import { useActiveSection } from './hooks/useActiveSection';
const ContactForm = lazy(() => import('./components/ContactForm'));
const enter = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } };
function App() { const { theme, toggleTheme } = useTheme(); const active = useActiveSection(navigation.map((item) => item.id)); const [openExperience, setOpenExperience] = useState<number | null>(0); return <><Navigation items={navigation} active={active} theme={theme} onThemeToggle={toggleTheme}/><main>
  <section className="relative overflow-hidden"><div className="mx-auto grid min-h-[calc(100vh-4rem)] max-w-6xl items-center gap-14 px-6 py-20 md:grid-cols-[1.25fr_.75fr] md:py-28"><motion.div initial="hidden" animate="show" transition={{ staggerChildren: .12 }}><motion.p variants={enter} className="eyebrow">Quality engineering, deliberately</motion.p><motion.h1 variants={enter} className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[1.04] tracking-[-.045em] sm:text-6xl lg:text-7xl">{profile.name}<span className="text-brand">.</span></motion.h1><motion.p variants={enter} className="mt-5 font-display text-2xl text-muted md:text-3xl">{profile.role}</motion.p><motion.p variants={enter} className="mt-7 max-w-xl text-lg leading-8 text-muted">{profile.tagline}</motion.p><motion.div variants={enter} className="mt-9 flex flex-wrap gap-3"><a className="button-primary" href={resume.file} download><FiDownload/> Download résumé</a><a className="button-secondary" href="#contact">Contact me <FiArrowDownRight/></a></motion.div></motion.div><motion.div initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .25 }} className="relative mx-auto w-full max-w-sm"><div className="aspect-[4/5] overflow-hidden rounded-2xl border border-line bg-panel"><img src={profile.portrait} alt={`Portrait of ${profile.name}`} className="h-full w-full object-cover" loading="eager" onError={(event) => { event.currentTarget.style.display='none'; }}/><div className="grid h-full place-items-center p-10 text-center text-muted">Add your portrait at <code className="mt-2 text-xs">public/portrait.jpg</code></div></div><div className="absolute -bottom-4 -left-4 rounded-xl border border-line bg-background px-4 py-3 text-sm shadow-xl"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-500"/>Open to opportunities</div></motion.div></div></section>
  <Section id="about" eyebrow="01 — About" title="Reliable software starts with useful questions."><div className="grid gap-8 md:grid-cols-2"><p className="max-w-xl text-xl leading-8 text-muted">{profile.about}</p><div className="grid grid-cols-2 gap-3">{[['Focus','Quality systems'],['Approach','Human + automation'],['Based in',profile.location],['Available for','New challenges']].map(([label,value]) => <div key={label} className="card p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 font-display font-medium">{value}</p></div>)}</div></div></Section>
  <Section id="skills" eyebrow="02 — Capabilities" title="Tools are only as good as the judgment behind them." className="bg-subtle"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{skills.map((group, index) => <motion.article initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.05}} key={group.group} className="card p-6"><h3 className="font-display text-xl font-medium">{group.group}</h3><div className="mt-5 flex flex-wrap gap-2">{group.items.map((skill) => <span key={skill} className="pill">{skill}</span>)}</div></motion.article>)}</div></Section>
  <Section id="experience" eyebrow="03 — Experience" title="Calm process. Confident releases."><div className="relative ml-3 border-l border-line pl-8 md:ml-5">{experience.map((job,index) => <article key={job.company} className="relative mb-8"><span className="absolute -left-[41px] top-7 h-3 w-3 rounded-full border-[3px] border-background bg-brand"/><button onClick={() => setOpenExperience(openExperience === index ? null : index)} className="card w-full p-6 text-left transition hover:border-zinc-500" aria-expanded={openExperience === index}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-display text-xl font-medium">{job.role}</p><p className="mt-1 text-muted">{job.company}</p></div><p className="text-sm text-muted">{job.period}</p></div><p className="mt-5 leading-7 text-muted">{job.summary}</p>{openExperience === index && <motion.ul initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} className="mt-5 space-y-2 border-t border-line pt-5 text-sm text-muted">{job.highlights.map((highlight) => <li key={highlight}>— {highlight}</li>)}</motion.ul>}</button></article>)}</div></Section>
  <Section id="certifications" eyebrow="04 — Learning" title="Credentials backed by practice." className="bg-subtle"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{certifications.map((cert) => <article key={cert.title} className="card p-6"><p className="text-sm text-brand">{cert.year}</p><h3 className="mt-4 font-display text-xl font-medium">{cert.title}</h3><p className="mt-2 text-muted">{cert.issuer}</p></article>)}</div></Section>
  <Section id="agents" eyebrow="05 — AI Work" title="Intelligence with a quality bar."><div className="grid gap-5 lg:grid-cols-2">{agents.map((agent) => <article key={agent.title} className="card group flex flex-col p-7"><h3 className="font-display text-2xl font-medium">{agent.title}</h3><p className="mt-4 leading-7 text-muted">{agent.overview}</p><dl className="mt-7 grid gap-5 border-t border-line pt-6 text-sm"><div><dt className="font-semibold">The problem</dt><dd className="mt-1 text-muted">{agent.problem}</dd></div><div><dt className="font-semibold">The solution</dt><dd className="mt-1 text-muted">{agent.solution}</dd></div></dl><div className="mt-7 flex items-center justify-between"><div className="flex flex-wrap gap-2">{agent.technology.map((item)=><span className="pill" key={item}>{item}</span>)}</div><a href={agent.url} className="icon-button" target="_blank" rel="noreferrer" aria-label={`View ${agent.title} on GitHub`}><FiArrowUpRight/></a></div></article>)}</div></Section>
  <GithubSection />
  <Section id="resume" eyebrow="07 — Résumé" title="A concise record of impact." className="bg-subtle"><div className="card flex flex-col justify-between gap-6 p-7 md:flex-row md:items-center"><p className="max-w-xl text-lg leading-7 text-muted">For the full story, including detailed responsibilities and outcomes, view or download my résumé.</p><div className="flex gap-3"><a className="button-primary" href={resume.file} download><FiDownload/> PDF</a><a className="button-secondary" href={resume.online}>View online <FiArrowUpRight/></a></div></div></Section>
  <Section id="contact" eyebrow="08 — Contact" title="Let’s build confidence into the next release."><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-lg leading-8 text-muted">I’m always happy to discuss quality systems, automation strategy, and thoughtful product delivery.</p><div className="mt-8 space-y-4 text-sm"><a className="contact-link" href={`mailto:${profile.email}`}><FiMail/>{profile.email}</a><a className="contact-link" href={`tel:${profile.phone}`}><FiPhone/>{profile.phone}</a><span className="contact-link"><FiMapPin/>{profile.location}</span><a className="contact-link" href={socials.find((s)=>s.label==='LinkedIn')?.url} target="_blank" rel="noreferrer"><FiLinkedin/> LinkedIn</a></div></div><Suspense fallback={<div className="card h-80 animate-pulse"/>}><ContactForm /></Suspense></div></Section>
  </main><footer className="border-t border-line py-8"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-6 text-sm text-muted"><p>© {new Date().getFullYear()} {profile.name}. Built with care.</p><div className="flex gap-4"><a href={socials[0].url} aria-label="GitHub"><FiGithub/></a><a href={socials[1].url} aria-label="LinkedIn"><FiLinkedin/></a><button onClick={() => window.scrollTo({top:0,behavior:'smooth'})}>Back to top ↑</button></div></div></footer></> }
function GithubSection() { const [repos,setRepos]=useState<import('./types').Repository[]|null>(null); const [error,setError]=useState(false); useEffect(() => { let current = true; import('./services/github').then(({getFeaturedRepositories})=>getFeaturedRepositories(import.meta.env.VITE_GITHUB_USERNAME || 'infantalfredjoy').then((data) => current && setRepos(data)).catch(()=>current && setError(true))); return () => { current = false; }; }, []); return <Section id="github" eyebrow="06 — GitHub" title="Work that lives in the open.">{!repos&&!error&&<p className="text-muted">Loading repositories…</p>}{error&&<p className="text-muted">Repository highlights are temporarily unavailable.</p>}{repos&&<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{repos.map((repo)=><a key={repo.id} href={repo.html_url} target="_blank" rel="noreferrer" className="card block p-6 transition hover:border-zinc-500"><div className="flex items-center justify-between"><h3 className="font-display text-lg font-medium">{repo.name}</h3><FiArrowUpRight/></div><p className="mt-4 min-h-12 text-sm leading-6 text-muted">{repo.description || 'Open-source work and experiments.'}</p><div className="mt-6 flex gap-4 text-sm text-muted"><span>{repo.language || 'Code'}</span><span className="flex items-center gap-1"><FiStar/> {repo.stargazers_count}</span></div></a>)}</div>}</Section> }
export default App;
